### ISSUE TITLE
Create public-facing EssSharp API documentation (primarily via docfx)

### ISSUE THREAD

**Issue by billybooth** [appliedolap/EssSharp#38]

**Comment by billybooth** [comment]
Public-facing DocFx documentation now lives at:
https://developer.appliedolap.com/EssSharp

**Comment by timtow** [comment]
Do we need to put an entry point link on the developer.appliedolap.com page itself?

**Comment by billybooth** [comment]
I don't think that it's necessary, but we can if we want to. With the next release, we will link to it from the NuGet readme as well.
